In [1]:
import numpy as np
import pandas as pd

In [2]:
df_data = pd.read_csv('all_data.csv', index_col=0)
df_data

,Date,Price,Open,High,Low,Vol.,Change %,000001.SZ,000002.SZ,000063.SZ,...,601919.SS,601939.SS,601985.SS,601988.SS,601989.SS,601998.SS,603259.SS,603288.SS,603501.SS,603993.SS
0,2023-08-31,"12,601.99","12,656.82","12,681.05","12,588.64",NaN,-0.43%,11.130000,13.640000,35.450001,...,9.800000,6.000000,7.200000,3.750000,4.200000,5.460000,81.500000,39.099998,92.019997,5.730000
1,2023-08-30,"12,656.82","12,706.49","12,752.50","12,641.28",NaN,-0.39%,11.130000,14.200000,35.200001,...,9.780000,5.980000,7.090000,3.760000,4.270000,5.460000,82.139999,39.820000,91.709999,5.780000
2,2023-08-29,"12,706.49","12,640.81","12,811.37","12,614.18",NaN,0.52%,11.310000,14.200000,34.910000,...,9.540000,6.030000,7.150000,3.800000,4.320000,5.530000,81.260002,40.000000,90.239998,5.770000
3,2023-08-28,"12,640.81","12,494.73","13,122.61","12,494.73",NaN,1.17%,11.520000,14.050000,34.270000,...,9.540000,6.140000,7.200000,3.840000,4.300000,5.600000,79.220001,39.820000,88.199997,5.730000
4,2023-08-25,"12,494.73","12,489.20","12,569.83","12,419.67",NaN,0.04%,11.230000,13.440000,33.709999,...,9.390000,6.040000,7.220000,3.790000,4.270000,5.510000,79.059998,40.080002,89.180000,5.800000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1881,2016-01-08,"9,906.67","9,750.36","10,058.83","9,648.70",NaN,1.60%,8.336792,17.120953,15.380937,...,3.876821,3.677842,7.125658,2.448837,8.527672,4.528543,NaN,13.267058,NaN,3.702521
1882,2016-01-07,"9,750.36","10,297.45","10,297.45","9,712.31",NaN,-5.31%,8.201845,17.120953,14.954479,...,3.908860,3.644649,6.956804,2.442392,8.438115,4.431453,NaN,13.135785,NaN,3.530521
1883,2016-01-06,"10,297.45","10,178.16","10,314.27","10,129.51",NaN,1.17%,8.644175,17.120953,16.470776,...,4.336058,3.744229,7.590009,2.506835,9.353572,4.743528,NaN,14.202908,NaN,3.919783
1884,2016-01-05,"10,178.16","10,101.04","10,259.92","9,903.94",NaN,0.76%,8.546713,17.120953,16.319147,...,4.170519,3.704397,7.463368,2.487502,9.283918,4.688048,NaN,14.232551,NaN,3.566731
1885,2016-01-04,"10,101.04","10,711.64","10,711.64","10,098.94",NaN,-5.70%,8.494230,17.120953,16.034840,...,4.336058,3.717675,7.395825,2.493947,8.666981,4.688048,NaN,14.016586,NaN,3.639152

In [3]:
df_weights = pd.read_csv('all_weights.csv', index_col=0)
df_weights

FileNotFoundError: [Errno 2] No such file or directory: 'all_weights.csv'

In [ ]:
df_ic = pd.read_excel('industryClassification.xlsx')
df_ic

In [ ]:
df_weights['code'].unique()

In [ ]:
df = df_ic[df_ic['securityCode'].isin(['600519','300750','000858','600036','601318','600900','002594','300760','000568','601888','601166','601398','600809','603288','601012','600309','601288','600276','002352','002714','300059','601899','600030','002304','601668','000001','300015','601138','002475','600000','603259','601328','601088','601225','600028','600887','002142','601601','600438','601988','000002','601857','600690','600104','601658','300999','601633','601939','601319','601998','600016','601169','600837','601766','000333','601211','601989','600048','601818','601390','601688','601186','000776','001979','002415','000166','601006','601628','601985','601336','601800','002736','002252','600018','600011','600606','002027','601238','000725','600050','600019','601229','000651','600585','601360','600009','300498','300122','002607','601066','601816','600031','601919','002024','600010','601669','601727','600023','300014','600436','000063','603501','600346','603993'])]

In [ ]:
df = df.drop(labels=['cics3rd_code','cics3rdNameEn','cics4thCode','cics4thNameEn','csrc1stCode','csrc1stNameEn','csrc2ndCode','csrc2ndNameEn'],axis=1)

In [ ]:
df = df.reset_index()

In [ ]:
df = df.drop('index',axis=1)

In [ ]:
df['securityCode'] = df['securityCode'].apply(lambda x: x + '.ss' if x[0:2] == '60' else x + '.sz')

In [ ]:
df = df.rename(columns={'securityCode': 'code', 'securityNameEn': 'name', 'cics1stCode': 'sectorCode', 'cics1stNameEn': 'sector', 'cics2ndCode': 'indGroupCode', 'cics2ndNameEn': 'indGroup'})

In [ ]:
df

In [ ]:
df['sector'].unique()

In [ ]:
df['sector'].value_counts()

In [ ]:
df['indGroup'].value_counts()

In [ ]:
my_map = {'Financials': 1, 'Industrials': 0, 'Consumer Discretionary': 0, 'Consumer Staples': 0, 'Health Care': 1, 'Materials': 0, 'Information Technology': 1, 'Real Estate': 0, 'Utilities': 1, 'Energy': 0, 'Communication Services': 1}

In [ ]:
df['indClassification'] = df['sector']
df['indClassification'] = df['indClassification'].map(my_map)
df

In [ ]:
df['indClassification'].value_counts()